### ISSUE TITLE
Don't allow organisation access

### ISSUE THREAD

**Issue by mcintyre321** [gjtorikian/addalicense.com#20]
I was about to use addalicense.com, but it looks like it would have access to the organisations I am a member of, and I can't disable this. This would give the app access to my client's code, which would be a big problem.

**Comment by gjtorikian** [comment]
Hi @mcintyre321! Recently GitHub changed the way that organization app policies work: https://help.github.com/articles/enabling-third-party-application-restrictions-for-your-organization/

I encourage you to enable third-party app restrictions for your org. Any OAuth app would have access to your org--not just this one. Hope that helps!

**Comment by mcintyre321** [comment]
Thanks for the info - I don't control the organisations though, I've merely contracted for them in the past, so I guess I'll have to contact the admins.
